/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.kvdb;

public class Access {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Access(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Access obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        kvdbAccessJNI.delete_Access(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Access() {
    this(kvdbAccessJNI.new_Access(), true);
  }

  public boolean open(String log_dir, String data_dir) {
    return kvdbAccessJNI.Access_open(swigCPtr, this, log_dir, data_dir);
  }

  public boolean write(String key, String value) {
    return kvdbAccessJNI.Access_write(swigCPtr, this, key, value);
  }

  public boolean update(String key, String value) {
    return kvdbAccessJNI.Access_update(swigCPtr, this, key, value);
  }

  public String read(String key) {
    return kvdbAccessJNI.Access_read(swigCPtr, this, key);
  }

  public boolean remove(String key) {
    return kvdbAccessJNI.Access_remove(swigCPtr, this, key);
  }

}
